security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        BackEndBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: ROLE_ADMIN }
        user_db:
            entity: { class: BackEndBundle:User, property: username }
    firewalls:
        main:
            pattern: /.*
            form_login:
                login_path: /god/login
                check_path: /god/login_check
                default_target_path: /god/product/list #TODO: change this
            logout:
                path:   /god/logout
                target: /god/product/list #TODO: change this
            security: true
            anonymous: true
    access_control:
        - { path: /god/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /god/user, roles: ROLE_ADMIN }
        - { path: /god, roles: ROLE_USER }
