# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    backend.twig_extensions:
        class: BackEndBundle\Twig\BackEndExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    frontend.twig_extensions:
        class: FrontEndBundle\Twig\FrontEndExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    product_crawler:
        class: BackEndBundle\Utils\ProductCrawler\ProductCrawler
        arguments: ["@doctrine.orm.default_entity_manager"]
