<?php

namespace BackEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], ['id' => 'DESC']);
    }
}
