BackEndBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: BackEndBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        price:
            type: decimal
            precision: 10
            scale: '2'
        description:
            type: text
            nullable: true
        image_url:
            type: text
            nullable: true
        rating:
            type: integer
            nullable: true
    manyToOne:
        category:
            targetEntity: BackEndBundle\Entity\Category
            inversedBy: products
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
