front_end_homepage:
    path: /
    defaults: { _controller: FrontEndBundle:Product:index }

front_end_category_page:
    path: /category/{categoryName}
    defaults: { _controller: FrontEndBundle:Category:categoryPage }

front_end_product_page:
    path: /product/{id}
    defaults: { _controller: FrontEndBundle:Product:productPage }

front_end_cart_add:
    path: /cart/add
    methods: [POST]
    defaults: { _controller: FrontEndBundle:Cart:addToCart }
    condition: "request.isXMLHttpRequest()"

front_end_cart_get:
    path: /cart/get
    methods: [POST]
    defaults: { _controller: FrontEndBundle:Cart:getCart }
    condition: "request.isXMLHttpRequest()"

front_end_checkout_cart_page:
    path: /checkout/cart
    defaults: { _controller: FrontEndBundle:Checkout:cartPage }

front_end_checkout_order_info_page:
    path: /checkout/order-info
    defaults: { _controller: FrontEndBundle:Checkout:orderInfoPage }

front_end_checkout_complete_page:
    path: /checkout/complete
    defaults: { _controller: FrontEndBundle:Checkout:checkoutCompletePage }