login_route:
    path:     /login
    defaults: { _controller: BackEndBundle:Security:login }

login_check:
    path:     /login_check

logout:
    path:     /logout

back_end_product_list:
    path:     /product/list
    defaults: { _controller: BackEndBundle:Product:list }

back_end_product_new:
    path:     /product/new
    defaults: { _controller: BackEndBundle:Product:new }

back_end_product_edit:
    path:     /product/{id}/edit
    defaults: { _controller: BackEndBundle:Product:edit }

back_end_product_delete:
    path:     /product/{id}/delete
    defaults: { _controller: BackEndBundle:Product:delete }

back_end_category_list:
    path:     /category/list
    defaults: { _controller: BackEndBundle:Category:list }

back_end_category_new:
    path:     /category/new
    defaults: { _controller: BackEndBundle:Category:new }

back_end_category_edit:
    path:     /category/{id}/edit
    defaults: { _controller: BackEndBundle:Category:edit }

back_end_category_delete:
    path:     /category/{id}/delete
    defaults: { _controller: BackEndBundle:Category:delete }

back_end_user_list:
    path:     /user/list
    defaults: { _controller: BackEndBundle:User:list }